### **Building Neural Networks from Scratch**

y = w1x1 + w2x2 + w3x3 + ... + wnxn + b

Where b = bias.

### **Creating a Basic Neuron with 3 Inputs**

In [20]:
inputs =  [1.0, 2.0, 3.0]    # Input values
weights = [0.5, -1.5, 2.0]   # Weights associated with each input
bias =    1.0                # Bias term

# Calculate the output using the neuron equation
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias

# Print the output
print(output)

4.5


### **Creating a Layer of Neurons with 4 Inputs and 3 Neurons**

In [21]:
inputs =   [1.5, 2.5, 3.5, 4.0]       # Input values

weights1 = [0.1, 0.2, -0.3, 0.4]      # Weights for the first neuron
weights2 = [0.4, -0.5, 0.6, -0.7]     # Weights for the second neuron
weights3 = [-0.8, 0.9, -1.0, 1.1]     # Weights for the third neuron

bias1 =    0.5                        # Bias for the first neuron
bias2 =    1.0                        # Bias for the second neuron
bias3 =    1.5                        # Bias for the third neuron

# Calculate the output for each neuron
output = [
    inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
    inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
    inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3
]

print(output)

[1.7000000000000002, -0.34999999999999964, 3.45]


### **Doing Dot Product with a Layer of Neurons and Multiple Inputs**

y = w.x + b

In [22]:
import numpy as np

inputs =  np.array([1.5, 2.5, 3.5, 4.0])  # Convert inputs to a NumPy array
weights = np.array([
    [0.1, 0.2, -0.3, 0.4],
    [0.4, -0.5, 0.6, -0.7],
    [-0.8, 0.9, -1.0, 1.1]
])
biases =  np.array([0.5, 1.0, 1.5])  # Convert biases to a NumPy array

output = np.dot(weights, inputs) + biases
print(output)


[ 1.70000005 -0.35000002  3.45000005]


### **Layers and Objects**

In [23]:
import numpy as np 
np.random.seed(0)

X = np.array([[1.5, 2.5, 3.5, 4.0],
              [2.0, 5.0, -1.0, 2.0],
              [-1.5, 2.7, 3.3, -0.8]])

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print("Layer 01\n", layer1.output)
layer2.forward(layer1.output)
print("Layer 02\n", layer2.output)

Layer 01
 [[ 0.20417337  1.404173    0.29327127  0.4781426   0.19649717]
 [-0.08349796  0.70846415  0.00293357  0.44701523  0.3636054 ]
 [-0.50763243  0.5568842   0.07987796 -0.34889573  0.04553042]]
Layer 02
 [[ 0.16812852 -0.11359761]
 [ 0.14100316 -0.01340469]
 [ 0.20124978 -0.07290616]]


### **All in One with Hidden Layer Activation Function**

In [24]:
!pip install nnfs

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.1.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


### Imports and Initialization:

In [25]:
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data 

nnfs.init()

nnfs (Neural Networks from Scratch) is a custom library that provides tools and datasets for learning neural networks from scratch.

from nnfs.datasets import spiral_data: Imports a specific function spiral_data from the datasets module within nnfs. This function generates a dataset commonly used to test neural network algorithms.

nnfs.init(): Initializes nnfs. This typically sets up configurations or initializes necessary resources within the nnfs library.

### Generating Dataset:

In [26]:
X, y = spiral_data(100, 3)   

The above function call generates a synthetic dataset suitable for testing neural networks. 

It creates 100 data points (X) and their corresponding labels (y) with 3 classes. 

This dataset is often used to visualize and test classification algorithms.

### Defining Layer_Dense Class:

In [27]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

Layer_Dense Class: This class represents a dense (fully connected) layer in a neural network.

__init__(self, n_inputs, n_neurons): Constructor method that initializes the layer with random weights and biases.

self.weights: Initialized with random values using np.random.randn(n_inputs, n_neurons), scaled by 0.10. These are the connection weights between input neurons and output neurons.

self.biases: Initialized as zeros, shaped as (1, n_neurons). These biases are added to each neuron in the layer.

forward(self, inputs): Method that performs the forward pass computation of the layer.

inputs: Input data passed to the layer.

self.output: This calculates the weighted sum of inputs plus biases, which forms the output of the layer.

### Defining Activation_ReLU Class:

In [28]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

Activation_ReLU Class: Represents the ReLU (Rectified Linear Unit) activation function, which introduces non-linearity into the neural network.

forward(self, inputs): Method that performs the ReLU activation function on the input data.

self.output: This operation replaces any negative values in inputs with zero, effectively activating neurons only when their input is positive.

### Creating and Using Layers:

In [29]:
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)
print("Layer 01\n", layer1.output)
activation1.forward(layer1.output)
print("Layer 02\n", activation1.output)

Layer 01
 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-8.35815910e-04 -7.90404272e-04 -1.33452227e-03  4.65504505e-04
   4.56846210e-05]
 [-2.39994470e-03  5.93469958e-05 -2.24808278e-03  2.03573116e-04
   6.10024377e-04]
 ...
 [ 1.13291524e-01 -1.89262271e-01 -2.06855070e-02  8.11079666e-02
  -6.71350807e-02]
 [ 1.34588361e-01 -1.43197834e-01  3.09493970e-02  5.66337556e-02
  -6.29687458e-02]
 [ 1.07817926e-01 -2.00809643e-01 -3.37579325e-02  8.72561932e-02
  -6.81458861e-02]]
Layer 02
 [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-

**Creating Layers:**

layer1 = Layer_Dense(2, 5): Creates a dense layer (Layer_Dense object) with 2 input neurons and 5 output neurons. layer1 initializes its weights and biases upon instantiation.

activation1 = Activation_ReLU(): Creates an activation function (Activation_ReLU object).

**Forward Pass:**
layer1.forward(X): Performs the forward pass through layer1, applying its weights and biases to the dataset X (spiral_data). This computes layer1.output.

**Applying Activation:** 
activation1.forward(layer1.output): Applies the ReLU activation function (Activation_ReLU) to the output of layer1. This computes activation1.output.